### ISSUE TITLE
Project needs a licensing and licence file in the root

### ISSUE THREAD

**Issue by teolemon** [rufuspollock-okfn/opd-product-browser-android#20]

**Comment by PhilippePlagnol** [comment]
There's no licence because POD doesn't produce information. It structures and organize the public data provided by manufacturer through packaging.

This issue list is about the android app, for the licencing subject, please go on the mailing list

**Comment by tfmorris** [comment]
If the software doesn't have a license, it isn't open source.

**Comment by PhilippePlagnol** [comment]
yes I understand what you want to say and I reopen the issue

**Comment by PhilippePlagnol** [comment]
Hello, it's done -> LICENSE.txt (MIT license)
