### ISSUE TITLE
Problem with internet connection

### ISSUE THREAD

**Issue by PhilippePlagnol** [rufuspollock-okfn/opd-product-browser-android#6]
Since the update to the version 1.00.4, some testers say that the message "no internet connection" always appears,...

**Comment by teolemon** [comment]
![screenshot_2013-11-04-18-48-30](https://f.cloud.github.com/assets/1689815/1466986/1ccd2d8a-457a-11e3-812e-1013368f4fbc.png)

**Comment by PhilippePlagnol** [comment]
Do you use wifi ? of 3G ? 
I only placed on the manifest the permission for INTERNET,... I don't know if it automatically allows wifi

**Comment by PhilippePlagnol** [comment]
do you have access to this url from your phone ? http://www.product-open-data.com/product/3095757343101

**Comment by teolemon** [comment]
WIFI and 3G were on, but only Wifi was effective. IMHO, there should be an
option to get an offline copy of the db for your country that could be
refreshed. You typically don't get any network in supermarkets.

**Comment by PhilippePlagnol** [comment]
It seams that the link can't be opened when you have the problem

**Comment by PhilippePlagnol** [comment]
Yes, internet access in supermarket is an other battle,... ;) 
can you open this ttp://www.product-open-data.com/product/3095757343101

**Comment by teolemon** [comment]
As a matter of fact, no issue. I'll try with that exact barcode

**Comment by teolemon** [comment]
Opens the link fine in Chrome Mobile, but same message on manual input in the app

**Comment by PhilippePlagnol** [comment]
Teolemon, could you give your version of android please ?

**Comment by teolemon** [comment]
stock 4.3 (Nexus 4)

---

Pierre Slamich - pierre@slamich.net

**Comment by PhilippePlagnol** [comment]
Hello, could you check that it's fixed ?
the last version should be available (1.00.08) 
The version is displayed on the menu

**Comment by teolemon** [comment]
Succès :-)

sent from mobile

**Comment by PhilippePlagnol** [comment]
Ouf !! I spent many hours to understand the problem arggg perfect :)

**Comment by PhilippePlagnol** [comment]
I used Thread to fix it (it was working with 2.2.3 but not with versions like 4.2.2) AsyncTask
