### ISSUE TITLE
Offline lookup option

### ISSUE THREAD

**Issue by teolemon** [rufuspollock-okfn/opd-product-browser-android#8]

**Comment by PhilippePlagnol** [comment]
Very good point : "what id the supermarket doesn't allow internet connection,..." the fact to store the database in the phone is not possible because of the volume so it's more a big battle to ask supermarkets to let consumer to have access to internet

**Comment by teolemon** [comment]
Do you have a sense on how large it would be with and without photos for a single country ?
That's a problem also faced by OpenFoodFacts for both lookups and contributions (people need to be able to snap pictures to contribute and lookup nutrition data even in a degraded environnement)

**Comment by PhilippePlagnol** [comment]
picture are 150*150 and data are very big (4 Go ,...) 

An POD is a DataWareHouse aiming to contain all existing gtin codes the notion of contry is only for registration (which GS1 gived the GCP to the manufaturer). A product can be sold in many countries,....

Open fact Food and all the smartphone app (listed here http://product.okfn.org/smartphone-apps/) has the same problem: a store can choose to cut all internet connection to avoid that consumers get other information than what they provide,...

**Comment by PhilippePlagnol** [comment]
If you don't have your answer, please reopen it
